-- MySQL Script generated by MySQL Workbench
-- Tue May 21 20:37:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuaio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuaio` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`));


-- -----------------------------------------------------
-- Table `mydb`.`orden de venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden de venta` (
  `id` INT NOT NULL,
  `fecha` DATETIME NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuaio` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
SHOW databases; 
USE mydb;    
SELECT * FROM usuaio;
SELECT * FROM `orden de venta`;


INSERT INTO `usuaio` (cedula , nombre , telefono, correo ) VALUES (1566599 , 'jose' , 0975652 , 'jose@hotmail.com');
INSERT INTO `orden de venta` (id , fecha , usuario_id ) VALUES (1 , '2024-05-21' , 1566599);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
