-- MySQL Script generated by MySQL Workbench
-- Wed May 22 14:15:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(32) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cedula`));


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `producto` VARCHAR(100) NOT NULL,
  `precio` FLOAT NOT NULL,
  `clave` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `clave_idx` (`clave` ASC) VISIBLE,
  CONSTRAINT `clave`
    FOREIGN KEY (`clave`)
    REFERENCES `mydb`.`usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE mydb;

SELECT * FROM usuario;
SELECT * FROM ventas;

INSERT INTO usuario (cedula , nombre , apellido , telefono, correo , direccion) VALUES (123456789 , "maria" , "jose" , 097564586 , "maria@hotmail.com", "quito");
INSERT INTO usuario (cedula , nombre , apellido , telefono, correo , direccion) VALUES (123454456 , "mario" , "nava" , 097566698 , "nava@hotmail.com", "ambato");

INSERT INTO ventas (fecha , producto , precio , clave) VALUES ('2024-05-22' , "leche" , 1.5 , 123456789);
INSERT INTO ventas (fecha , producto , precio , clave) VALUES ('2024-05-22' , "carne" , 3.5 , 123454456);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
